name: pre-commit hooks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v5

    - name: python setup
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'

    - name: install uv
      run: pip install uv

    - name: install dependencies
      run: uv sync --locked

    - name: run pre-commit hooks
      run: uv run pre-commit run --all-files
